export const themes = {
  bento: {
    '--bg-color': '#2d394d',
    '--main-color': '#ff7a90',
    '--caret-color': '#ff7a90',
    '--sub-color': '#4a768d',
    '--sub-alt-color': '#263041',
    '--text-color': '#fffaf8',
    '--error-color': '#ee2a3a',
    '--error-extra-color': '#f04040',
    '--colorful-error-color': '#fc2032',
    '--colorful-error-extra-color': '#f04040',
  },
  wild: {
    '--bg-color': '#262a33',
    '--main-color': '#43ffaf',
    '--caret-color': '#43ffaf',
    '--sub-color': '#526777',
    '--sub-alt-color': '#1f232c',
    '--text-color': '#e5f7ef',
    '--error-color': '#ff5f5f',
    '--error-extra-color': '#d22a2a',
    '--colorful-error-color': '#ff5f5f',
    '--colorful-error-extra-color': '#d22a2a',
  },
  berry: {
    '--bg-color': '#2d394d',
    '--main-color': '#ff7a90',
    '--caret-color': '#ff7a90',
    '--sub-color': '#4a768d',
    '--sub-alt-color': '#263041',
    '--text-color': '#fffaf8',
    '--error-color': '#ee2a3a',
    '--error-extra-color': '#f04040',
    '--colorful-error-color': '#fc2032',
    '--colorful-error-extra-color': '#f04040',
  },
  gruvbox: {
    '--bg-color': '#fbf1c7',
    '--main-color': '#689d6a',
    '--caret-color': '#689d6a',
    '--sub-color': '#a89984',
    '--sub-alt-color': '#daceae',
    '--text-color': '#3c3836',
    '--error-color': '#cc241d',
    '--error-extra-color': '#9d0006',
    '--colorful-error-color': '#cc241d',
    '--colorful-error-extra-color': '#9d0006',
  },
  honey: {
    '--bg-color': '#f2aa00',
    '--main-color': '#fff546',
    '--caret-color': '#795200',
    '--sub-color': '#a66b00',
    '--sub-alt-color': '#e19e00',
    '--text-color': '#f3eecb',
    '--error-color': '#df3333',
    '--error-extra-color': '#6d1f1f',
    '--colorful-error-color': '#df3333',
    '--colorful-error-extra-color': '#6d1f1f',
  },
  muted: {
    '--bg-color': '#525252',
    '--main-color': '#c5b4e3',
    '--caret-color': '#b1e4e3',
    '--sub-color': '#939eae',
    '--sub-alt-color': '#494949',
    '--text-color': '#b1e4e3',
    '--error-color': '#edc1cd',
    '--error-extra-color': '#edc1cd',
    '--colorful-error-color': '#edc1cd',
    '--colorful-error-extra-color': '#edc1cd',
  },
  paper: {
    '--bg-color': '#eee',
    '--main-color': '#444',
    '--caret-color': '#444',
    '--sub-color': '#b2b2b2',
    '--sub-alt-color': '#ddd',
    '--text-color': '#444',
    '--error-color': '#d70000',
    '--error-extra-color': '#d70000',
    '--colorful-error-color': '#d70000',
    '--colorful-error-extra-color': '#d70000',
  },
  rose: {
    '--bg-color': '#fffaf3',
    '--main-color': '#56949f',
    '--caret-color': '#ea9d34',
    '--sub-color': '#c4a7e7',
    '--sub-alt-color': '#f0e9df',
    '--text-color': '#286983',
    '--error-color': '#b4637a',
    '--error-extra-color': '#d7827e',
    '--colorful-error-color': '#b4637a',
    '--colorful-error-extra-color': '#d7827e',
  },
  shoko: {
    '--bg-color': '#ced7e0',
    '--main-color': '#81c4dd',
    '--caret-color': '#81c4dd',
    '--sub-color': '#7599b1',
    '--sub-alt-color': '#b7cada',
    '--text-color': '#3b4c58',
    '--error-color': '#bf616a',
    '--error-extra-color': '#793e44',
    '--colorful-error-color': '#bf616a',
    '--colorful-error-extra-color': '#793e44',
  },
  sweden: {
    '--bg-color': '#0058a3',
    '--main-color': '#ffcc02',
    '--caret-color': '#b5b5b5',
    '--sub-color': '#57abdb',
    '--sub-alt-color': '#024f8e',
    '--text-color': '#fff',
    '--error-color': '#e74040',
    '--error-extra-color': '#a22f2f',
    '--colorful-error-color': '#f56674',
    '--colorful-error-extra-color': '#e33546',
  },
  vscode: {
    '--bg-color': '#1e1e1e',
    '--main-color': '#007acc',
    '--caret-color': '#569cd6',
    '--sub-color': '#4d4d4d',
    '--sub-alt-color': '#191919',
    '--text-color': '#d4d4d4',
    '--error-color': '#f44747',
    '--error-extra-color': '#f44747',
    '--colorful-error-color': '#f44747',
    '--colorful-error-extra-color': '#f44747',
  },
};

export const loadTheme = (themeName = 'bento') => {
  const colors = themes[themeName];
  Object.keys(colors).forEach(key => {
    document.documentElement.style.setProperty(key, colors[key]);
  });
};
